package com.example.android.kkf.APIUtilies;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface ELHIServiceEvents
{
    public void Starting();
    public void Completed(ELHOperationResult result);
}
